### ISSUE TITLE
Indexstore missing references when 2 types in different imported modules have the same name

### ISSUE THREAD

**Issue by dylansturg** [swiftlang/swift#67499]
**Description**

The indexstore data for a Swift file is missing references specifically for constructor symbols when calling an initializer on a type, where the a type with the same name is declared in 2 different modules that are both imported in the file.

**Steps to reproduce**

Create at 2 different Swift modules to import as dependencies, both containing a `struct` with the same name:

File 1 - `Deps.swift`
```swift
public struct FooBar {
	public init(depsInit: String) {}
}
```

File 2 - `OtherDeps.swift`
```swift
public struct FooBar {
	public init(otherDepsInit: String) {}
}
```

File 3 - `Indexing.swift`
```swift
import Deps
import OtherDeps

func foo() {
	let _ = FooBar(depsInit: "")
}
```

Compute the indexstore for `Indexing.swift`; a simple way is to call `sourcekitd-test -req index`:

```
swiftc \
  -sdk /var/db/xcode_select_link//Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk \
  -target x86_64-apple-ios15.0-simulator \
  -emit-module-path .build/Deps.swiftmodule \
  Deps.swift

swiftc \
  -sdk /var/db/xcode_select_link//Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk \
  -target x86_64-apple-ios15.0-simulator \
  -emit-module-path .build/OtherDeps.swiftmodule \
  OtherDeps.swift

sourcekitd-test  \
  -req index Indexing.swift -- \
  -target x86_64-apple-ios15.0-simulator \
  -sdk /var/db/xcode_select_link/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk \
  -F/var/db/xcode_select_link/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks \
  -F/var/db/xcode_select_link/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/Library/Frameworks \
  -I/var/db/xcode_select_link/Platforms/iPhoneSimulator.platform/Developer/usr/lib \
  -I$(pwd)/.build \
  -module-name Indexing \
  -emit-object \
  Indexing.swift 
```

Index output:
```yaml
key.entities: [
    {
      key.kind: source.lang.swift.ref.module,
      key.name: "Deps",
      key.usr: "c:@M@Deps",
      key.line: 2,
      key.column: 8
    },
    {
      key.kind: source.lang.swift.ref.module,
      key.name: "OtherDeps",
      key.usr: "c:@M@OtherDeps",
      key.line: 3,
      key.column: 8
    },
    {
      key.kind: source.lang.swift.decl.function.free,
      key.name: "foo()",
      key.usr: "s:8Indexing3fooyyF",
      key.line: 5,
      key.column: 6,
      key.effective_access: source.decl.effective_access.internal
    }
  ]
```

**Expected behavior**

I expected to see a constructor reference to `FooBar.init` in the indexstore. Instead, there's no reference to the struct `FooBar` nor any reference to the initializer that is being called. The code can be compiled and works as expected, so the compiler is resolving everything correctly.

The indexing works as expected if fully qualified names are used instead.

**Environment**
- Swift compiler version info Swift version 5.9-dev (LLVM edfa23b742ff932, Swift 18d8d9b752723b6)
- Xcode version info Xcode 14.3, Build version 14E222b
- Deployment target: iOS 15.0

**Additional Context**

This also reproduces when the name collision occurs with a system framework like Foundation. If there's a user-defined `Data` type (separate from the one in Foundation) and its initializer is called in a file that also imports Foundation then the indexstore doesn't include references to that initializer.
