### ISSUE TITLE
Support `__swift_attr__` to APINotes

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftlang/swift#75819]
### Motivation

Currently, we have no way to mark Clang-imported declarations with arbitrary Swift attributes with APINotes files. For example, it can be problematic when migrating to strict concurrency model because we can't add concurrency related markers without modifying system header files.

### Proposed solution

Add `SwiftAttr` field to APINotes like below

```yaml
Name: SwiftWASILibc
Globals:
- Name: errno
  SwiftAttr: ["nonisolated(unsafe)"]
```
